import Header from "../components/AppHeader";
import NoiseBackground from "../components/NoiseBackground";
import type { Metadata } from "next";
import { Geist, Inter, Space_Grotesk } from "next/font/google";
import "../globals.css";
import { SessionProvider } from "next-auth/react";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CineAI - Home",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body
          className={`${geist.variable} ${inter.variable} ${spaceGrotesk.variable} antialiased`}
        >
          <div className="relative min-h-screen bg-neutral-950 text-white">
            <div className="absolute inset-0 z-10 pointer-events-none overflow-hidden">
              <NoiseBackground
                patternSize={250}
                patternScaleX={1}
                patternScaleY={1}
                patternRefreshInterval={2}
                patternAlpha={5}
              />
            </div>
            <div className="relative z-20">
              <Header />
              <main className="px-4 pt-30">{children}</main>
            </div>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
