import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "../globals.css";
import { SessionProvider } from "next-auth/react";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CineAI",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body
          className={`${geist.variable} ${inter.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
